@host=http://localhost:5285

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Amichai",
    "astName": "Mantinband",
    "email": "amichai@mantinband.com",
    "password": "Amiko1232!"
}